import type { Metadata } from 'next';
import { ReactNode } from 'react';
import { Roboto } from 'next/font/google';
import './globals.css';
import { Locale, i18n } from '../../../i18n.config';

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
  children,
  params,
}: {
  children: ReactNode;
  params: { locale: Locale };
}) {
  return (
    <html lang={params.locale}>
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
