import './globals.css';
import type { Metadata } from 'next';
import { ReactNode } from 'react';
import { Roboto } from 'next/font/google';
import 'react-toastify/dist/ReactToastify.css';

import { Locale, i18n } from '../../../i18n.config';
import { AuthProvider } from '@/context/AuthContext/AuthContext';
import { CartProvider } from '@/context/CartContext/CartContext';
import ToastifyAppearance from '@/components/ToastifyAppearance/ToastifyAppearance';

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Tess-ract',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
  children,
  params,
}: {
  children: ReactNode;
  params: { locale: Locale };
}) {
  return (
    <html lang={params.locale}>
      <AuthProvider>
        <CartProvider>
          <body className={roboto.className}>
            {children}
            <ToastifyAppearance />
          </body>
        </CartProvider>
      </AuthProvider>
    </html>
  );
}
